//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogbookApi.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jetstrea_LogbookEntities : DbContext
    {
        public jetstrea_LogbookEntities()
            : base("name=jetstrea_LogbookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Airfield> Airfield { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<Totals> Totals { get; set; }
        public virtual DbSet<Trace> Trace { get; set; }
    }
}
