//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogbookApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int PageNumber { get; set; }
        public int StartFlight { get; set; }
        public int EndFlight { get; set; }
        public int TotalMin { get; set; }
        public int P1SMin { get; set; }
        public int P1SFlight { get; set; }
        public int P1MMin { get; set; }
        public int P1MFlight { get; set; }
        public int P2Min { get; set; }
        public int P2Flight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
